#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.blockMesh

# Meshing
runApplication blockMesh
touch case.foam

# Output message
echo Mesh created