#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

# Clean run time folders
foamListTimes -rm
rm log.simpleFoam
rm -rf postProcessing

runApplication simpleFoam 
postProcess -func singleGraph -latestTime

echo
echo Case ended

#------------------------------------------------------------------------------
